### ISSUE TITLE
Running 100000 iterations of a single POST call seems to break the reporter

### ISSUE THREAD

**Issue by jbnok** [postmanlabs/newman#935]
**_Version and environment information:_**

 1. Newman Version (can be found via `newman -v`): _3.4.3_
 2. OS details (type, version, and architecture): _RHEL Linux_
 3. Are you using Newman as a library, or via the CLI? _CLI_
 3. Did you encounter this recently, or has this bug always been there: _Recently_
 4. Expected behaviour: _I should get a test report like I did when I did this with 10000_
 5. Command / script used to run Newman: _(This is from a Jenkins Execution) /usr/local/lib/node_modules/newman/bin/newman.js run ${COLLECTION_NAME} -e ${ENVIRONMENT_NAME} -d serverInfo.csv -n ${COUNT} -r html,cli,json,junit --insecure
_
 6. Sample collection, and auxilliary files (minus the sensitive details): _**All I can give you is the exception i see at the end of the console log**

usr/local/lib/node_modules/newman/lib/reporters/json/index.js:17
            content: JSON.stringify(_.omit(o.summary, 'exports'), 0, 2)
                          ^

RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/newman/lib/reporters/json/index.js:17:27)
    at EventEmitter.emit (/usr/local/lib/node_modules/newman/node_modules/eventemitter3/index.js:151:33)
    at done (/usr/local/lib/node_modules/newman/lib/run/index.js:199:29)
    at /usr/local/lib/node_modules/newman/node_modules/postman-runtime/lib/backpack/index.js:56:34
    at PostmanCollectionRun._process (/usr/local/lib/node_modules/newman/node_modules/postman-runtime/lib/runner/run.js:112:20)
    at PostmanCollectionRun.<anonymous> (/usr/local/lib/node_modules/newman/node_modules/postman-runtime/lib/runner/run.js:123:18)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)_

**_Steps to reproduce the problem:_**

1. Run a newman job with a CSV file and 100K instances of a single call

**Comment by czardoz** [comment]
Hmm, this is because the output report has too much of data. 
This can only be solved by creating a streaming JSON reporter, using something like https://www.npmjs.com/package/stream-json

**Comment by jbnok** [comment]
This is something anyone that's going to performance test an API is going to try... This should be supported out of the box (especially when we're not  using this programatically... which is a requirement for the configuration you're suggesting).

This should and must be supported out of the box.

**Comment by czardoz** [comment]
@jbnok, the current reporters are not designed for load testing scenarios, but I can see why it will be useful : thumbs-up:

**Comment by Paramagnetic** [comment]
I wrote a reporter that basically just cuts out a bunch of stuff. It cut what was a 92.5 MB report  (in the standard JSON reporter) down to 315 KB, while keeping what I consider the important data. This doesn't use a streamer, still JSON.stringify, but I haven't run into the Invalid String Length issue since switching to it. Hopefully this is useful to other people as well: https://www.npmjs.com/package/newman-reporter-json-light

**Comment by awaisabir** [comment]
Was running into the same issue. I'll try your reporter out @Paramagnetic !

**Comment by sandello-alkr** [comment]
Same issue here... Would be useful to be able to filter out successful runs.

**Comment by xiaweixing** [comment]
@Paramagnetic Recently we also got this same issue, and considering there are more people experience the same, have you considered to create a pull request to submit your solution to postman repo?  Thank you.

**Comment by shamasis** [comment]
This should be resolved as we add reported flags to trim request and response payloads. But I really like the light JSON reporter. Will recommend your reporter meanwhile. @Paramagnetic

**Comment by michal19256** [comment]
I have installed @Paramagnetic json-light-reporter but how am I supposed to use that?  I placed it in newman/lib/reporters and trying: "**newman run collection.json --globals globals.json -r newman-reporter-json-light**" in the bash console. But "please install reporter using npm" information shows after Enter.

**Comment by michal19256** [comment]
> This should be resolved as we add reported flags to trim request and response payloads. But I really like the light JSON reporter. Will recommend your reporter meanwhile. @Paramagnetic

Hello @shamasis,
 is there any situation update? Is possible to run plenty of requests in single run (limitless run)?

**Comment by cainzhong** [comment]
I use big-json to generate the summary.json instead of using JSON.stringify(). It works. The code looks like below.
```
let bigJson = require('big-json')
function saveBigObjectAsFile(bigObject, filePath) {
	const stringifyStream = bigJson.createStringifyStream({
		body: bigObject
	})
	let writeStream = fs.createWriteStream(filePath)
	return new Promise((resolve) => {
		stringifyStream.on('data', (chunk) => {
			writeStream.write(chunk)
		})
		stringifyStream.on('end', () => {
			logger.log('info', 'All data has been saved to %s', filePath)
			resolve()
		})
	})
}
```

**Comment by vbakshi123-star** [comment]
@

> This should be resolved as we add reported flags to trim request and response payloads. But I really like the light JSON reporter. Will recommend your reporter meanwhile. @Paramagnetic

This is still an issue while running it in Azure Dev Ops. newman version 5.3.2 running only 2500 iterations.
